[build]
  command = "pip install nltk && python -c \"import nltk; nltk.download('vader_lexicon'); import shutil; shutil.copy('templates/index.html', 'static/index.html')\""
  functions = "netlify/functions"
  publish = "static"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200